###
POST http://127.0.0.1:8000/auth/users/login/ 
Content-Type: application/json 

{
    "username":"admin",
    "password":"123"
}

###
POST http://127.0.0.1:8000/auth/users/login/refresh/ 
Content-Type: application/json 

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NDY4NTMwNCwiaWF0IjoxNzYyMDkzMzA0LCJqdGkiOiI5NzRjN2IyZjNjZTU0MDNkYjc0NTU0Mjg4MjM5MDdjNyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.-jYqYy7A25IzJtnp4rIpitHjnDs8b8Be8uL7QpZkzr0" 
}
 
###
POST http://127.0.0.1:8000/auth/users/register/
Content-Type: application/json 

{
    "username":"admin",
    "first_name": "Nur mamun",
    "password":"123",
    "email":"admin@gmail.com"
}

###
GET http://127.0.0.1:8000/auth/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzY1ODMxLCJpYXQiOjE3NjIxNjEwMzEsImp0aSI6ImFjY2RlOTU2NDg4ZjQ3N2M4Yzc5NjIwZDkwN2E1YjM4IiwidXNlcm5hbWUiOiJhZG1pbiJ9.kCOGJWmBQF_stf2fYIqiOwvn_zE3Ml8-n4CPTZwZBKk
Content-Type: application/json 

{  
  "first_name": " cx cx"  
}


###
POST http://127.0.0.1:8000/auth/users/me/change-password/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNzY1ODMxLCJpYXQiOjE3NjIxNjEwMzEsImp0aSI6ImFjY2RlOTU2NDg4ZjQ3N2M4Yzc5NjIwZDkwN2E1YjM4IiwidXNlcm5hbWUiOiJhZG1pbiJ9.kCOGJWmBQF_stf2fYIqiOwvn_zE3Ml8-n4CPTZwZBKk
Content-Type: application/json 

{  
  "old_password": "123",  
  "new_password": "123"  
}
